language: android

jdk:
  - oraclejdk8

components:
    - tools
    - tools
    - platform-tools #latest
    - build-tools-26.0.1
    - android-26
    - extra-android-m2repository
    - extra-google-m2repository

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

notifications:
  email: false

script:
  - ./gradlew assemble check
